"use client";

import { persistor, store } from "@/redux/store";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider as ReduxProvider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider store={store}>
          <PersistGate persistor={persistor}>{children}</PersistGate>
        </ReduxProvider>
      </body>
    </html>
  );
}
